### PR TITLE
Add several new placeholders

### PR DESCRIPTION
**Pull request by Aaron1011**
This PR adds several new placeholders:

* 'trainer_team_#_hiddenpower' - The type of the pokemon's  Hidden Power
move. If the pokemon doesn't know this move, then this placeholder
returns the type that it would be if they were to learn it.
* 'trainer_team_#_ivtotalsum' - The sum of the pokemon's IV stats
* 'trainer_team_#_evtotalsum' - The sum of the pokemon's EV stats
* 'trainer_team_#_ivtotalpercent' - The sum of the pokemon's IV stats as
a percentage of the maximum possible IV sum
* 'trainer_team_#_evtotalpercent' - The sum of the pokemon's EV stats as
a percentage of the maximum possible EV sum
* 'trainer_team_#_texturelocation' - The ResourceLocation of the
pokemon's sprite texture.
* 'trainer_team_#_customtexture' - The ResourcELocation of the pokemon's
custom texture, or 'N/A' if the pokemon has no custom texture
* 'trainer_team_#_form' - The form number of the pokemon

Additionally, this commit adds integration with the 'entity-particles'
plugin. If the 'entity-particles' is installed, the following
placeholder will be enabled:

* 'trainer_team_#_aura' - The ID of the 'entity-particles' effect
currently possesed by the pokemon.

If the pokemon has no 'entity-particles' effect, or 'entity-particles'
is not installed, the placeholder returns 'N/A'

This PR is based on this Sponge forum request: https://forums.spongepowered.org/t/pixelmon-placeholders-plugin-addons/24424

Note that this PR is currently depending on my fork of 'entity-particles'. This is purely to make it easier to test this PR in development, since 'entity-particles' has a few bugs that make it difficult to run in a development environment. However, this PR is fully compatible with the latest release of 'entity-particles' (2.1). In production, it can be run alongside the normal 'entity-particles' jar.

### CODE REVIEW

**Comment by randombyte-developer** [comment]
Merged all PRs.

**Comment by hqppyz** [comment]
The pr looks good, there are some changes that i need to do tho (like some placeholders name, some minor style choice, the hardcoded unbreedable and untradable), and i have some other changes in my pc which i forgot to push, but i can do all that by myself.

I'm not sure about why you're using your fork of PlaceholderAPI tho, mind explaining that? I hope it doesn't break any support for the original PlaceholderAPI v4.4.

EDIT: I'm pretty sure the reason is the same as the other fork, i just want you to confirm

**Comment by Aaron1011** [comment]
@happyzleaf: Yeah, that was just to allow testing on the client. I didn't make any changes other than bugfixes on my fork of PlaveholderAPI

**Comment by hqppyz** [comment]
I'm ready to merge, i'll probably push the update tomorrow, or in the weekend

**Pull request merged**
